name: macOS

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  schedule:
      - cron: 0 0 * * 0

jobs:
  Qt:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        qt: [5.13.2]
        os: [macos-latest]

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Install Qt (macOS)
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}
    - name: Configure and compile VESC Tool (MacOS)
      run: ./build_macos
    - name: Upload vesc_tool-macOS
      uses: actions/upload-artifact@v1
      with:
        name: vesc_tool-macOS
        path: build/macos

